### ISSUE TITLE
No matching distribution found for torch==0.2.0.post3 

### ISSUE THREAD

**Issue by HandsomeDevilv112** [deepsound-project/samplernn-pytorch#15]
I'm on the pytorch docker, and I'm extremely confused about what I'm doing wrong at this point. Any assistance is appreciated.

root@6b27a1f07b65:~/samplernn-pytorch# pip install -r requirements.txt
Collecting librosa==0.5.1 (from -r requirements.txt (line 1))
  Using cached librosa-0.5.1.tar.gz
Collecting matplotlib==2.1.0 (from -r requirements.txt (line 2))
  Using cached matplotlib-2.1.0-cp36-cp36m-manylinux1_x86_64.whl
Collecting natsort==5.1.0 (from -r requirements.txt (line 3))
  Using cached natsort-5.1.0-py2.py3-none-any.whl
Collecting torch==0.2.0.post3 (from -r requirements.txt (line 4))
  Could not find a version that satisfies the requirement torch==0.2.0.post3 (from -r requirements.txt (line 4)) (from versions: 0.1.2, 0.1.2.post1)
No matching distribution found for torch==0.2.0.post3 (from -r requirements.txt (line 4))

Edit: I can get it working without cuda. At this point is torch==0.2.0.post3 vital?

**Comment by veltman** [comment]
FWIW I ran into the same issue and just updated `requirements.txt` to `torch==0.3.1` and it seemed to work OK.

**Comment by HandsomeDevilv112** [comment]
thank you for reminding me about this, my apologies for not updating when I found a solution. Checking "print(torch.__version__)" I receive 0.4.0a0+542fbcc. Checking requirements.txt, I seem to have left it on default and installed separately.
Your answer sounds way more elegant.
Closing, as the real issue was between the keyboard and chair.
