### ISSUE TITLE
download dataset from youtube 

### ISSUE THREAD

**Issue by guozixunnicolas** [deepsound-project/samplernn-pytorch#27]
when I run the code _cd datasets
./download-from-youtube.sh "https://www.youtube.com/watch?v=EhO_MrRfftU" 8 piano_

_"." is not recognized as an internal or external command, operable or batch file_ shows up. 

Anyone can tell me how to deal with this?

**Comment by manoharvhr** [comment]
You need youtube-dl and ffmpeg.

Install this via pip or conda
